# .github/workflows/fetch-jobs.yml

name: Daily Job Fetching

on:
schedule:
# Run at 6 AM EST (11 AM UTC) every day
- cron: ‘0 11 * * *’

# Allow manual triggering for testing

workflow_dispatch:

jobs:
fetch-jobs:
runs-on: ubuntu-latest

    steps:
    - name: Trigger Job Fetching
      run: |
        curl -X POST \
          "${{ secrets.APP_URL }}/cron/fetch-jobs?cron_secret=${{ secrets.SECRET_KEY }}" \
          --fail-with-body
      
    - name: Check Status
      if: success()
      run: echo "✅ Job fetching completed successfully"
      
    - name: Handle Failure  
      if: failure()
      run: |
        echo "❌ Job fetching failed"
        exit 1